paused: false
# While this is true blocks will not be regenerated and any blocks broken during it
# won't be restored by this plugin. But blocks broken before and after it will.

regen-delay: "30 minutes"
# Delay between each regeneration
# Unit can be [seconds, minutes, hours, days]

alert:
  before: "&a[BlockRegenerator] Regeneration in 10 seconds..."
  # Message displayed before the regeneration
  # Leave empty to disable
  before-delay: "10 seconds"
  # It will be displayed X units before regen
  # Unit can be [seconds, minutes, hours, days]
  after: "&a[BlockRegenerator] Regeneration done!"
  # Message displayed just after the regeneration
  # Leave empty to disable

min-time: "2 days"
# Minimum time after which a block is considered as "old" and will be regenerated
# Can be [seconds, minutes, hours, days]

max-blocks: "10"
# Number of blocks restored at each regeneration
# Can be of the format "X%" if you want it to be proportional to the total
# Can be of the format "X" if you want it to be static (always the same amount)

efficiency: 90
# Efficiency of the regeneration
# Only X% of blocks will be restored, the rest will be ignored
# "90" = some blocks won't be restored
# "100" = all blocks will be restored
# "50" = half the blocks will be restored

events:
  broken:
    enabled: true
    # Restore broken blocks
    ignore-creative: false
    # Ignore blocks broken by players in creative gamemode
  placed:
    enabled: true
    # Restore placed blocks?
    ignore-creative: false
    # Ignore blocks placed by players in creative gamemode
  burnt:
    enabled: true
    # Restore burnt blocks
  exploded:
    enabled: true
    # Restore explosions
    type: whitelist
    # Whitelist: only restore explosions caused by these entities
    # Blacklist: do not restore explosions caused by these entities
    list:
      - creeper
      - primed_tnt

controllers:
  worlds:
    enabled: true
    type: whitelist
    # Whitelist: only restore blocks in these worlds
    # Blacklist: do not restore blocks in these worlds
    list:
      - world
      - world_nether
      - world_the_end
  materials:
    enabled: true
    type: blacklist
    # Whitelist: only restore blocks materials in these materials
    # Blacklist: do not restore blocks materials in these materials
    list:
      - bedrock
      - "minecraft:chest" # Explicit names are only available for 1.13

extras:
  force-log: true
  # true: the plugin logs/saves the block in attempt to rollback it when it will match the filter
  # false: the plugin simply ignores blocks that does not match the filter
  # aka "If you want achieve rollback in now unclaimed areas"

