#     __         _    ____  __   ___
#    |__) |__|  /_\   ___/ |  \ |__  \  /
#	 |  \ |  | /   \ /___  |__/ |___  \/
#
#   If you like my softwares or you just want to support me, I'd enjoy donations.
#   By donating, you're going to encourage me to continue developing quality softwares.
#   And you'll be added to the donators list!
#
#   Click here to donate: http://dev.rhaz.fr/donate
#

debugging: false
#I wouldn't change this as it makes console and in game chat very very spammy.

regen-delay: "30 minutes"
# Delay between each regeneration
# Can be [seconds, minutes, hours, days]

min-time: "2 days"
# Minimum time after which a block is considered as "old" and will be regenerated
# Can be [seconds, minutes, hours, days]

max-blocks: 10
# Number of blocks restored at each regeneration

percentage-efficiency: 90
# X% of blocks will be restored, the rest will be ignored

paused: false
#While this is true blocks will not be regenerated and any blocks broken during it
#won't be restored by this plugin. But blocks broken before and after it will.

restore-destroyed: true
# Should this plugin restore destroyed blocks? (this includes explosions)

restore-placed: true
# Should this plugin restore placed blocks?

ignore-creative: false
# Blocks broken/placed by people in creative wont be restored if this is true.

worlds:
  enabled: true
  type: whitelist
  # Whitelist: only restore blocks in these worlds
  # Blacklist: do not restore blocks in these worlds
  worlds:
  - world
  - world_nether
  - world_the_end

materials:
  enabled: true
  type: blacklist
  # Whitelist: only restore blocks materials in these materials
  # Blacklist: do not restore blocks materials in these materials
  materials:
  - "BLOCK_NAME:ID" # (example: STONE:0 would be just normal stone)

worldguard:
  enabled: false
  #If you do not have WorldGuard leave this disabled
  type: whitelist
  # Whitelist: only restore blocks in these regions
  # Blacklist: do not restore blocks in these regions
  regions:
  - "region_name"

factions:
  enabled: false
  type: whitelist
  # Whitelist: only restore blocks in these factions
  # Blacklist: do not restore blocks in these factions
  factions:
  - "Wilderness"

griefprevention:
  enabled: false
  admins-claims: false
  # Should this plugin restore admins claims?
  players-claims: true
  # Should this plugin restore players claims?
