name: BlockRegenerator
version: ${project.version}
main: fr.rhaz.minecraft.BlockRegeneratorPlugin
author: Hazae41
depend: [Kotlin4MC]
softdepend: [WorldGuard, Factions, GriefPrevention]

commands:
    blockregen:
        usage: "/<command>"

permissions:
    blockregen.*:
        children:
            blockregen.force: true
            blockregen.toggle: true
            blockregen.clear: true
            blockregen.debug: true
            blockregen.reload: true
